spring.config.activate.on-profile: dev

spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          timeout: # read timeout
          starttls:
            enable:

token:
  access-key:
  refresh-key:
  access-time:
  refresh-time:

verify:
  email-timeout:
  phone-timeout:

map:
  google:
    project-id:
    key:
    base-url:
    place-url:
    place-detail-url:
    geocode-url:
