spring:
  profiles:
    group:
      local: [ "api-local", "shared-local" ]
      dev: [ "api-dev", "shared-dev" ]
      test: [ "api-test", "shared-test" ]
      stg: [ "api-stg", "shared-stg" ]
      prod: [ "api-prod", "shared-prod" ]
    default: local

  application:
    name: api
  servlet:
    multipart:
      file-size-threshold: 2KB # 파일이 디스크에 기록되기 시작하는 임계값
      max-file-size: 10MB # 파일 하나당 최대 사이즈
      max-request-size: 50MB # 요청당 최대 사이즈

  pid:
    file: api.pid

  lifecycle:
    timeout-per-shutdown-phase: 35s

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          timeout:
          starttls:
            enable:

server:
  compression:
    enabled: true
  shutdown: graceful
  port: ${API_SERVER_PORT:8080}
app:
  version: ${APP_VERSION:}
  ip:
    public: localhost
    local: localhost
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, loggers
  metrics:
    tags:
      application: api
      app_version: ${app.version}
      stage: local
  health:
    diskspace:
      path: /

whitelist:
  metrics: ${API_WHITELIST_METRICS}
  private: ${API_WHITELIST_PRIVATE:0:0:0:0:0:0:0:1, localhost, 127.0.0.1}
  private-instance: 10.0

token:
  access-key:
  refresh-key:
  access-time:
  refresh-time:
