spring:
  application:
    name: api
  servlet:
    multipart:
      file-size-threshold: 2KB # 파일이 디스크에 기록되기 시작하는 임계값
      max-file-size: 10MB # 파일 하나당 최대 사이즈
      max-request-size: 50MB # 요청당 최대 사이즈
  pid:
    file: api.pid
  lifecycle:
    timeout-per-shutdown-phase: 35s
server:
  compression:
    enabled: true
  shutdown: graceful
  port: ${AICREATION_SERVER_PORT:8080}
app:
  version: ${APP_VERSION:}
  ip:
    public: localhost
    local: localhost
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, loggers
  metrics:
    tags:
      application: api
      app_version: ${app.version}
      stage: local
  health:
    diskspace:
      path: /
