spring.config.activate.on-profile: stg

spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          timeout: # read timeout
          starttls:
            enable:

token:
  access-key:
  refresh-key:
  access-time:
  refresh-time:

verify:
  email-timeout:
  phone-timeout:
