version: "3.8"

services:
  db:
    container_name: ph-db
    image: postgres:15
    volumes:
      - /home/.system/docker-data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=postgres
      - POSTGRES_USER=ph
      - POSTGRES_PASSWORD=ph
  redis:
    container_name: ph-redis
    image: redis:alpine3.19
    command: redis-server --port 6379
    volumes:
      - /home/.system/docker-data/redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
