spring:
  datasource:
    hikari:
      username: ph
      password: ph
      maximum-pool-size: 10
      schema: public
      jdbc-url: ${JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
  flyway:
    locations: classpath:/db/migration # migration 파일들이 위치하는 directory
    sql-migration-suffixes: sql        # 파일 확장자
    baseline-on-migrate: true          # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 0                # 최초 버전 정보
    default-schema: public             # flyway 가 관리할 스키마
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      ssl:
        enabled: false
